version: "3.7"

services: 
  mongo:
    image: mongo
    ports:
      - 27017:27017
  
  mongo-ui:
    image: mongo-express
    ports:
      - 8080:8081
  
  utilisateurs:
    build: .
    environment: 
      - MONGO_HOST=mongo
    ports:
      - 9000:9000